### ISSUE TITLE
TODOs to finish packem

### ISSUE THREAD

**Issue by prisis** [visulima/packem#2]
## TODOs:

- [x] Watch Mode 
- [x] D.TS generation
- [x] Style
	- [x] less
	- [x] sass
	- [x] css
	- [x] css.module
	- [x] url 
- [x] let the user choose between swc, esbuild and sucrase as transformer
- [ ] commands
	- [ ] ~create migration command to migrate from tsup etc.~
	- [x] create a init command, to setup the "packem.config.ts" file and transformer
	- [ ] add validation command for package.js  and types
	  - [ ] used publint core
	  - [ ] used arethetypeswrong
  - [ ] add a prepare command, that check the source folder for Exports (with a interactive mode)
- [x] Support jsx/tsx
- [x] aliases
- [x] Auto preset
	- [x] Multiple Runtime
		- react-native
		- react-server
		- edge-light
	- [x] Env
- [x] Tests
- [ ] Docs
- [x] Remove jsx attributes on config
```typescript
const Tr = () => (<tr data-testid="test" data-test="test" />);

export default Tr;
```
- [x] wasm
- [x] Support preserve directives like "use client"
- [x] Add support for cjs interop for default and named export
- [x] check source map 
- [x] Add file cache for some plugins

## Plugins
- [x] License update on bundled deps and types
- [x] Add Copy plugin
- [x] dynamicVars
- [ ] Support .node files https://github.com/visulima/packem/issues/5
- [ ] Create a plugin that preserves jsdocs, so the the docs a bundled, create a filter to ignore some of them.
- [ ] https://github.com/danielroe/unplugin-purge-polyfills
## Typescript
```
TypeScript supports some additional features in its resolver on top of the Node resolution algorithm. These are configured in tsconfig.json.

baseUrl - a root directory from which to resolve non-relative paths, in addition to node_modules.
paths - additional directories, relative to baseUrl, that should also be searched.
rootDirs - virtual directories that relative paths can be resolved from
```

- [x] Support tsconfig paths
- [x] Allow the use of rootDirs in tsconfig for resolving https://www.typescriptlang.org/tsconfig#rootDirs
- [ ] https://www.typescriptlang.org/tsconfig#moduleSuffixes
- [x]  TypeScript Decorators
- [x] Make TS optional
- [ ] Support for TypeScript project references https://www.typescriptlang.org/docs/handbook/project-references.html
- [x] Add the new isolated-declarations

**Comment by prisis** [comment]
Map package.json exports with .cjs or .mjs to the correct file, if .cts exist map it with .cjs and if .mts exists map it to .mjs else take .ts

**Comment by prisis** [comment]
- [ ] Check cache handling of the commonjs plugin, add a test to validate that it does not break on the second run, check @visulima/path package

**Comment by prisis** [comment]
- [ ] The licence plugin should remove the placeholders if a licence file is important from a different package that uses the same placeholders.

**Comment by prisis** [comment]
- [ ] Prefer publishConfig from package.json when defined
> I'd like to use the src/ dir (i.e., TS) vs. dist/ (i.e., JS) when using the package within the monorepo via the workspace: protocol. Essentially, I want to be able to define a different config when not published, relying on [pnpm's publishConfig](https://pnpm.io/package_json#publishconfig) to do the overrides when I publish to the npm registry:

```json
    "publishConfig": {
        "type": "module",
        "exports": {
            ".": {
                "types": "./dist/index.d.ts",
                "require": "./dist/index.js",
                "import": "./dist/index.mjs"
            }
        },
        "main": "./dist/index.js",
        "module": "./dist/index.mjs",
        "types": "./dist/index.d.ts"
    },
    "main": "./src/index.ts",
```

**Comment by prisis** [comment]
- [] improve speed with workers

**Comment by prisis** [comment]
- [ ] replace @antfu/install-pkg with something better

**Comment by prisis** [comment]
- [ ] fix swc transformer usage

**Comment by prisis** [comment]
- [ ] add isolated declaration to the init command

**Comment by prisis** [comment]
-[ ] add support for node10 type resolution 
-[ ] init should ask for it or check if types field exists 

- [ ] add a validation for it

**Comment by prisis** [comment]
- [ ] Add a validation for the package.json
	- [ ] it should validate all fields that are needed to publish a package

**Comment by prisis** [comment]
- [ ] add tests for monorepo use

**Comment by prisis** [comment]
- [ ] watch mode
  - [ ] remove files from the internal entry array if the file was deleted on the watch mode
  - [ ] add new files into the new internal entry array it the a file was created

**Comment by prisis** [comment]
- [ ] add support for workers
```js
worker = new Worker(new URL("./worker.js", import.meta.url), { type: "module" });
// or simply:
worker = new Worker("./worker.js", { type: "module" });
```

**Comment by prisis** [comment]
- [ ] Allow to set a builder before or after the core build

**Comment by prisis** [comment]
The open task will be work on in https://github.com/visulima/packem/issues/105
